todos/blueprints/user/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    render_template)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from lib.safe_next_url import safe_next_url
from todos.blueprints.user.decorators import anonymous_required
from todos.blueprints.user.models import User
from todos.blueprints.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    UpdateCredentials,
    UpdateUsernameForm)

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            if login_user(u, remember=True) and u.is_active():
                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('todo.list'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Identity or password is incorrect.', 'error')

    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Awesome, thanks for signing up!', 'success')
            return redirect(url_for('user.update_username'))

    return render_template('user/signup.html', form=form)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user.route('/settings/update_username', methods=['GET', 'POST'])
@login_required
def update_username():
    if current_user.username:
        flash('You already picked a username.', 'warning')
        return redirect(url_for('user.settings'))

    form = UpdateUsernameForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Sign up is complete, enjoy our services.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_username.html', form=form)


@user.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Your sign in settings have been updated.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

todos/blueprints/user/templates/user/begin_password_reset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Reset your password{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.begin_password_reset') %}
        <legend>Reset your password</legend>
        <p class="small help-block sm-margin-bottom">
          We'll send you an email to reset your password.
        </p>

        {% call f.form_group(form.identity, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Continue
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
                class="btn btn-default btn-block">
              Back to login
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

todos/blueprints/user/templates/user/login.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Sign in to access your account{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="title mb-3">
        <legend>Sign in to continue</legend>
      </div>
      {% call f.form_tag('user.login') %}
        {% call f.form_group(form.identity, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        {% call f.form_group(form.remember, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row mt-3">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Sign in
            </button>
          </div>
          <div class="col-md-6">
            <a href="{{ url_for('user.signup') }}"
               class="btn btn-default btn-block">
              Register
            </a>
          </div>
        </div>
      {% endcall %}

{#      <div class="text-center mt-3">#}
{#        <a href="{{ url_for('user.begin_password_reset') }}" class="text-muted">#}
{#          Forgot your password?#}
{#        </a>#}
{#      </div>#}
    </div>
  </div>
{% endblock %}

todos/blueprints/user/templates/user/password_reset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Enter a new password{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.password_reset') %}
        <legend>Enter a new password</legend>

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Continue
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
               class="btn btn-default btn-block">
              Back to login
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

todos/blueprints/user/templates/user/settings.html
{% extends 'layouts/app.html' %}

{% block title %}Account settings{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5">
      <h2>Settings</h2>
      <h4 class="text-muted margin-bottom">{{ current_user.email }}</h4>

      <div class="list-group">
        <a href="{{ url_for('user.update_credentials') }}"
           class="list-group-item">
          Update email and password
        </a>
        {% if current_user.username %}
          <span class="list-group-item quarter-faded text-muted">
            Your username is
            <strong>{{ current_user.username }}</strong>
          </span>
        {% else %}
          <a href="{{ url_for('user.update_username') }}"
             class="list-group-item">
            Pick a username
          </a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

todos/blueprints/user/templates/user/signup.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Sign up for a new account{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="title mb-3">
        <legend>Sign up today</legend>
      </div>

      {% call f.form_tag('user.signup') %}
        {% call f.form_group(form.email, css_class='sm-margin-bottom',
                             autofocus='autofocus',
                             placeholder='Email address') %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row mt-4">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Register
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
               class="btn btn-default btn-block">
              Looking to sign in?
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

todos/blueprints/user/templates/user/update_credentials.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Update your sign in information{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 offset-md-4">
      {% call f.form_tag('user.update_credentials') %}
        <legend>Update your sign in information</legend>
        <p class="small help-block sm-margin-bottom">
          Supply your current password to make any changes.
        </p>

        {% call f.form_group(form.current_password, css_class='lg-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        {% call f.form_group(form.email, css_class='sm-margin-bottom') %}
        {% endcall %}
        {% call f.form_group(form.password, css_class='sm-margin-bottom',
                             placeholder='New password (optional)') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Save
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.settings') }}"
               class="btn btn-default btn-block">
              Nevermind
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

todos/blueprints/user/templates/user/update_username.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Thanks for signing up{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5 col-md-push-1 col-md-offset-1 well">
      {% call f.form_tag('user.update_username') %}
        <legend>Pick a username</legend>
        <p class="small help-block sm-margin-bottom">
          You can only pick this once, make it count.
        </p>

        {% call f.form_group(form.username, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Save
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.settings') }}"
               class="btn btn-default btn-block">
              Do it later
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}