todos/blueprints/todo/models.py
from sqlalchemy import or_

from lib.util_sqlalchemy import ResourceMixin
from todos.blueprints.user.models import User
from todos.extensions import db


class Todo(ResourceMixin, db.Model):
    __tablename__ = 'todo'

    id = db.Column('id', db.Integer, primary_key=True, nullable=False)
    user_id = db.Column('user_id',
                        db.Integer,
                        db.ForeignKey('users.id',
                                      onupdate='CASCADE',
                                      ondelete='CASCADE'),
                        index=True,
                        nullable=False)
    description = db.Column('description', db.Text, nullable=False)
    todo_at = db.Column('todo_at', db.DateTime(), nullable=False)
    document = db.Column('document', db.String(50))
    is_complete = db.Column('is_complete', db.Boolean(), nullable=False, server_default='0')

    user = db.relationship(User, backref='todo')

    def get_storage_path(self):
        return f"{self.user_id}/{self.id}/{self.document}"

    @classmethod
    def bulk_complete(cls, ids):
        """
        Update 1 or more model instances.

        :param ids: List of ids to be updated
        :type ids: list
        :return: Number of updated instances
        """
        update_count = cls.query.filter(cls.id.in_(ids)).update(
            {cls.is_complete: True})
        db.session.commit()

        return update_count

    @classmethod
    def search(cls, query):
        """
        Search a resource by 1 or more fields.

        :param query: Search query
        :type query: str
        :return: SQLAlchemy filter
        """
        if not query:
            return ''

        search_query = '%{0}%'.format(query)
        search_chain = (User.email.ilike(search_query),
                        User.username.ilike(search_query))

        return or_(Todo.user.has(or_(*search_chain)), Todo.description.ilike(search_query))

todos/blueprints/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, DateTimeField, StringField, FileField
from wtforms.validators import DataRequired, Length, Optional

from lib.util_wtforms import ModelForm


class SearchForm(FlaskForm):
    q = StringField('Search terms', [Optional(), Length(1, 256)])


class TodoForm(ModelForm):
    description = TextAreaField('Description', validators=[
        DataRequired(),
        Length(1, 8192)
    ])

    todo_at = DateTimeField('Todo at', validators=[DataRequired()], format='%Y-%m-%d %H:%M:%S')

    document_file = FileField('Document')

todos/blueprints/todo/__init__.py
from todos.blueprints.todo.views import todo

todos/blueprints/todo/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user
from sqlalchemy import text

from lib.storage import Storage
from todos.blueprints.todo.forms import TodoForm, SearchForm
from todos.blueprints.todo.models import Todo

todo = Blueprint('todo', __name__, template_folder='templates')


@todo.before_request
@login_required
def before_request():
    """ Protect all of the todo endpoints. """
    pass


@todo.route('/todos', defaults={'page': 1})
@todo.route('/todos/page/<int:page>')
def list(page):
    search_form = SearchForm()

    sort_by = Todo.sort_by(request.args.get('sort', 'todo_at'),
                           request.args.get('direction', 'desc'))

    order_values = '{0} {1}'.format(sort_by[0], sort_by[1])

    search_query = request.args.get('q', '')

    todo_query = Todo.query

    if current_user.role == 'user':
        todo_query = todo_query.filter_by(user_id=current_user.id)

    if search_query:
        todo_query = todo_query.filter(Todo.search(search_query))

    todos = todo_query \
        .order_by(text(order_values)) \
        .paginate(page, 20, True)

    return render_template('todo/index.html',
                           form=search_form,
                           todos=todos)


@todo.route('/todo/create', methods=['GET', 'POST'])
def create():
    todo = Todo()

    form = TodoForm()

    if form.validate_on_submit():
        form.populate_obj(todo)

        if not todo.user_id:
            todo.user_id = current_user.id

        todo.save()

        file = request.files['document_file']

        if file:
            todo.document = file.filename
            _upload_document(file, todo)
            todo.save()

        flash('Todo been created successfully.', 'success')

        return redirect(url_for('todo.list'))

    return render_template('todo/create.html', form=form)


@todo.route('/todo/download_document/<int:id>')
def download_document(id):
    todo = Todo.query.get(id)

    if not todo.document:
        return redirect(url_for('todo.list'))

    storage = Storage()

    return redirect(storage.generate_presigned_url(path=todo.get_storage_path()))


@todo.route('/todo/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    todo = Todo.query.get(id)
    form = TodoForm(obj=todo)

    if form.validate_on_submit():
        form.populate_obj(todo)

        file = request.files['document_file']

        if file:
            todo.document = file.filename
            _upload_document(file, todo)

        todo.save()

        flash('Todo has been saved successfully.', 'success')
        return redirect(url_for('todo.list'))

    return render_template('todo/update.html', form=form, todo=todo)


@todo.route('/todo/complete/<int:id>', methods=['GET'])
def complete(id):
    todo = Todo.query.get(id)

    todo.is_complete = True
    todo.save()

    flash('Todo has been completed successfully.', 'success')
    return redirect(url_for('todo.list'))


@todo.route('/todos/bulk_delete', methods=['POST'])
def bulk_delete():
    ids = Todo.get_bulk_action_ids(request.form.getlist('bulk_ids'))

    if len(ids):
        delete_count = Todo.bulk_delete(ids)

        flash('{0} todo(s) were scheduled to be deleted.'.format(delete_count),
              'success')
    else:
        flash('No todos were deleted, something went wrong.', 'error')

    return redirect(url_for('todo.list'))


def _upload_document(file, todo):
    """
    Upload document to s3
    """
    storage = Storage()
    return storage.put(file=file, path=todo.get_storage_path())

todos/blueprints/todo/templates/macros/todo.html
{% macro icon_for_completed(todo) -%}
  {% if todo.is_complete %}
    <i class="fa fa-check text-success"></i>
  {% else %}
    <i class="fa fa-times text-warning"></i>
  {% endif %}
{% endmacro %}

todos/blueprints/todo/templates/todo/_form.html
{% import 'macros/form.html' as f with context %}

{% if request.endpoint.endswith('create') %}
  {% set endpoint = 'todo.create' %}
  {% set form_kwargs = {} %}
  {% set legend = 'Add a new todo' %}
  {% set button = 'Add' %}
{% else %}
  {% set endpoint = 'todo.update' %}
  {% set form_kwargs = {'id': todo.id} %}
  {% set legend = 'Update this todo' %}
  {% set button = 'Save' %}
{% endif %}

<div class="row">
  <div class="col-md-4 offset-md-4">
    {% call f.form_tag(endpoint, multipart=True, **form_kwargs) %}
      <legend>{{ legend }}</legend>

      {% call f.form_group(form.description, css_class='sm-margin-bottom',
                            rows='5',
                            autofocus='autofocus') %}
      {% endcall %}

      <div class="dt relative">
        {% call f.form_group(form.todo_at,
                              css_class='sm-margin-bottom datetimepicker-input') %}
        {% endcall %}
      </div>

      {% call f.form_group(form.document_file) %}
      {% endcall %}

      <div class="row mt-4">
        <div class="col-md-6">
          <button type="submit" class="btn btn-primary btn-block">
            {{ button }}
          </button>
        </div>
        <div class="col-md-6">
          <a href="{{ url_for('todo.list') }}"
              class="btn btn-default btn-block">
            Cancel
          </a>
        </div>
      </div>
    {% endcall %}
  </div>
</div>

todos/blueprints/todo/templates/todo/create.html
{% extends 'layouts/app.html' %}

{% block title %}Todos / Add{% endblock %}

{% block body %}
  {% include 'todo/_form.html' with context %}
{% endblock %}

todos/blueprints/todo/templates/todo/index.html
{% extends 'layouts/app.html' %}
{% import 'macros/items.html' as items %}
{% import 'macros/form.html' as f with context %}
{% import 'macros/todo.html' as helpers %}

{% block title %}Todo / List{% endblock %}

{% block body %}
  <div class="title">
    <h1>Todo list</h1>
    <a class="btn btn-outline-primary" href="{{ url_for('todo.create') }}">
      <i class="fa fa-plus mr-1"></i>
      Create todo
    </a>
  </div>
  {{ f.search('todo.list') }}

  {% if todos.total == 0 %}
    <h3>No results found</h3>

    {% if request.args.get('q') %}
      <p>Try limiting or removing your search terms.</p>
    {% else %}
      <p>There are no todos present,
         you should <a href="{{ url_for('todo.create') }}">Create</a>.</p>
    {% endif %}
  {% else %}
    {% call f.form_tag('todo.bulk_delete') %}
      <table class="table table-striped todo-table">
        <thead>
          <tr>
            <th class="checkbox">
              <label for="select_all"></label>
              <input id="select_all" name="select_all" type="checkbox">
            </th>
            <th class="col-header description">
              {{ items.sort('description', 'Description') }}
            </th>
            <th class="col-header todo-at">
              {{ items.sort('todo_at', 'Todo at') }}
            </th>
            {% if current_user.role == 'admin' %}
              <th class="col-header user">
                {{ items.sort('user', 'User') }}
              </th>
            {% endif %}
            <th class="col-header text-center completed">
              {{ items.sort('is_completed', 'Completed') }}
            </th>
            <th class="col-header text-center completed">
              {{ items.sort('document', 'Document') }}
            </th>
            <th class="col-header text-center actions">
              <i class="fa fa-cog"></i>
            </th>
            <th id="bulk_actions" colspan="5">
              <div class="form-inline">
                <span class="item-count mr-3" id="item-count"></span>
                <button type="submit"
                        class="btn btn-danger btn-sm">
                  Delete items
                </button>
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
        {% for todo in todos.items %}
          <tr>
            <td class="checkbox">
              <label for="bulk_ids"></label>
              <input class="checkbox-item" id="bulk_ids" name="bulk_ids"
                     type="checkbox" value="{{ todo.id }}">
            </td>
            <td class="description">
             {{ todo.description }}
            </td>
            <td class="todo-at">
              <time class="from-now"
                    data-datetime="{{ todo.todo_at }}">
                {{ todo.todo_at }}
              </time>
            </td>
            {% if current_user.role == 'admin' %}
              <td class="user">
                {% if todo.user.username %}
                  {{ todo.user.username + '(' + todo.user.email + ')' }}
                {% else %}
                  {{ todo.user.email }}
                {% endif %}
              </td>
            {% endif %}
            <td class="completed text-center">
              {{ helpers.icon_for_completed(todo) }}
            </td>
            <td class="completed text-center">
              {% if todo.document %}
                <a href="{{ url_for('todo.download_document', id=todo.id) }}">
                  <i class="fa fa-download" aria-hidden="true"></i>
                </a>
              {% endif %}
            </td>
            <td class="actions text-center">
              <button type="button"
                      class="btn btn-link dropdown-toggle"
                      data-toggle="dropdown"
                      aria-haspopup="true"
                      aria-expanded="false">
                <i class="fa fa-cog"></i>
              </button>
              <div class="dropdown-menu dropdown-menu-right">
                {% if not todo.is_complete %}
                  <a class="dropdown-item" href="{{ url_for('todo.complete', id=todo.id) }}" >
                    Mark as complete
                  </a>
                {% endif %}
                <a class="dropdown-item" href="{{ url_for('todo.update', id=todo.id) }}" >
                  Update
                </a>
              </div>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% endcall %}

    {{ items.paginate(todos) }}
  {% endif %}
{% endblock %}

todos/blueprints/todo/templates/todo/update.html
{% extends 'layouts/app.html' %}

{% block title %}Todos / Add{% endblock %}

{% block body %}
  {% include 'todo/_form.html' with context %}
{% endblock %}