todos/blueprints/user/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    render_template)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from lib.safe_next_url import safe_next_url
from todos.blueprints.user.decorators import anonymous_required
from todos.blueprints.user.models import User
from todos.blueprints.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    UpdateCredentials,
    UpdateUsernameForm)

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            if login_user(u, remember=True) and u.is_active():
                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('todo.list'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Identity or password is incorrect.', 'error')

    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Awesome, thanks for signing up!', 'success')
            return redirect(url_for('user.update_username'))

    return render_template('user/signup.html', form=form)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user.route('/settings/update_username', methods=['GET', 'POST'])
@login_required
def update_username():
    if current_user.username:
        flash('You already picked a username.', 'warning')
        return redirect(url_for('user.settings'))

    form = UpdateUsernameForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Sign up is complete, enjoy our services.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_username.html', form=form)


@user.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Your sign in settings have been updated.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

todos/templates/layouts/app.html
{% extends 'layouts/base.html' %}

{% block footer %}
{% endblock %}

todos/templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ static_url_for('static', filename='css/app.css') }}">
    <script defer src="{{ url_for('static', filename='js/app.js') }}"></script>
  </head>
  <body>
    {% include 'layouts/header.html' with context %}
    <main class="container mt-5">
      {{ flash.render() }}
      {% block body %}{% endblock %}
    </main>

    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="list-inline-item text-muted">Todo app &copy; 2020</li>
        </ul>
      </div>
    </footer>
  </body>
</html>

todos/templates/layouts/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('todo.list') }}">LOGO</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbar-collapse"
    aria-controls="navbar-collapse"
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div id="navbar-collapse" class="collapse navbar-collapse">
    <ul class="navbar-nav ml-auto">
      {% if current_user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('todo.list') }}">Todos</a>
      </li>
        {% if current_user.role == 'admin' %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin.users') }}">Users</a>
          </li>
        {% endif %}
        <li class="nav-item dropdown dropdown-menu-left">
          <a class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('user.settings') }}">Setting</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('user.logout') }}">Logout</a>
          </div>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.login') }}">Log in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.signup') }}">Sign up</a>
        </li>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>

todos/templates/layouts/login.html
{% extends 'layouts/base.html' %}

{% block footer %}
  <li><a href="{{ url_for('user.signup') }}">Sign up today</a></li>
{% endblock %}